### ISSUE TITLE
Updated demo page

### ISSUE THREAD

**Issue by arambert** [angular-ui/ui-slider#100]
Hi,
It seems that the demo (http://angular-ui.github.io/ui-slider/demo/demo.html) is outdated compared to the demo folder in this repository.
Is it possible to update it ?

Thanks

**Comment by PowerKiKi** [comment]
Demo is now at https://htmlpreview.github.io/?https://github.com/angular-ui/ui-slider/master/demo/index.html and is directly from master branch, so always in sync. 

Thanks for reporting.

**Comment by arambert** [comment]
Great, thank you very much !
