### ISSUE TITLE
Please publish 0.1.3 on NPM

### ISSUE THREAD

**Issue by rincedd** [angular-ui/ui-slider#101]
The release 0.1.3 has been published on Github some while ago, but could you also please publish the package to NPM. That would be greatly appreciated!

Thanks!

**Comment by PowerKiKi** [comment]
@nl0, you made the release 8 months ago on https://www.npmjs.com/package/angular-ui-slider. Would you be able to release the latest version and/or add me as collaborator on NPM so I can also make releases, please ?

**Comment by nl0** [comment]
@PowerKiKi what's your npm username?

**Comment by PowerKiKi** [comment]
@nl0 this would be me: https://www.npmjs.com/~powerkiki

**Comment by nl0** [comment]
@PowerKiKi i've made you an owner of the npm package. can i remove my fork then? its sole purpose was to publish the package to npm

**Comment by PowerKiKi** [comment]
thanks, I **think** it's save to delete your fork

@ProLoser, FYI you are also owner of https://www.npmjs.com/package/angular-ui-slider

**Comment by PowerKiKi** [comment]
0.2.1 is available

**Comment by ProLoser** [comment]
:+1:

**Comment by rincedd** [comment]
Thanks a lot! :+1:
