### ISSUE TITLE
add touchdrag support for handles - Feature

### ISSUE THREAD

**Issue by haxxxton** [angular-ui/ui-slider#102]
At the moment you can only tap the slider to move the handle(s) on mobile devices, would be nice to add drag support so that mobile devices get a similar experience to desktop

**Comment by PowerKiKi** [comment]
While this seems to be a good idea, I believe it is out of the scope of this project and should instead be implemented in [jQuery UI Slider](https://jqueryui.com/slider/).

**Comment by haxxxton** [comment]
perhaps integrating something like [touchpunch](https://github.com/furf/jquery-ui-touch-punch#readme) then?

**Comment by PowerKiKi** [comment]
This solution is also out of the scope of this project. There is nothing we should do here that you cannot already do by yourself.
