### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [angular-ui/ui-slider#107]
The newest version in Github is v0.3.1
But the newest version in npm is v0.3.0
Maybe should update the newest version in npm
Thanks

https://github.com/cdnjs/cdnjs/issues/6870
https://github.com/cdnjs/cdnjs/pull/7747#issuecomment-215815841

**Comment by PowerKiKi** [comment]
done

**Comment by kennynaoh** [comment]
Thanks
