### ISSUE TITLE
Remove jQuery UI dependency

### ISSUE THREAD

**Issue by j8** [angular-ui/ui-slider#27]
The slider should be independent from jQuery UI as the custom styling and functionality enhancement is real pain in the ass.

**Comment by PowerKiKi** [comment]
@douglasduteil where are we with the no-jquery version ? anything that should be merged here ? or did it become an independent project ? should this issue be closed ?

**Comment by douglasduteil** [comment]
Hi. Good timing @PowerKiKi I'm actually working on a new version of it :)
[my last attempt](https://github.com/douglasduteil/ui-slider-dirty)

**Comment by PowerKiKi** [comment]
let us know if/when something should be merged here

**Comment by PowerKiKi** [comment]
Closing as obsolete
