### ISSUE TITLE
Arbitrary javascript activity removes sliders from their holding DIVs

### ISSUE THREAD

**Issue by ness-EE** [angular-ui/ui-slider#60]
Whilst doing other arbitrary JavaScript work on a page that contains ui-sliders, triggered by a click event to, say, load in something somewhere completely different on the page, the sliders inexplicably disappear.

The only other js library loaded after subsequent click is jQuery DataTables

**Comment by PowerKiKi** [comment]
Please re-open with a reproducible use-case via plunkr if the issue still exists.
