### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by Bezmundo** [angular-ui/ui-slider#71]
When trying to implement within ie8 I get the following error:

```html
  TypeError: Object doesn't support this property or method<div class="ui-slider__thumb ng-pristine ng-valid" data-ng-model="question.selectedValue" data-name="input" data-ng-required="" data-ng-mouseleave="show = false" data-ng-mouseenter="show = true">
```
is there anyway to get support for ie8 without using the jquery version.

**Comment by PowerKiKi** [comment]
This project support Angular 1.3, and Angular 1.3 does not support IE8. There probably won't be any effort for IE8 compatibility. But if you submit a PR, it could still be merged.
