### ISSUE TITLE
slider is not working on mobile

### ISSUE THREAD

**Issue by akocmark** [angular-ui/ui-slider#84]
the slider widget doesn't work on my mobile, which is samsung grand duo. Do you know why is it now working on mobile? thanks!

**Comment by Marcrazyness** [comment]
Came across this same issue on mobile, pressing on the slider bar works but not the press and drag touch events.

**Comment by PowerKiKi** [comment]
Did you notice the same behavior with plain jQuery version ?

**Comment by Marcrazyness** [comment]
I hadn't checked before until now and yes I just duplicated here https://jqueryui.com/slider/. Just read around and found out that draggable doesn't work on mobile devices (http://stackoverflow.com/questions/9547613/jquery-ui-draggable-not-working-on-ios-devices), but that there are some hacks for it.

**Comment by patricklewis** [comment]
https://github.com/furf/jquery-ui-touch-punch provides a hack/fix for jQuery UI touch events on mobile; it fixed my problem of sliders not working on iOS Safari.

**Comment by Marcrazyness** [comment]
Thanks for the info @patricklewis! I ended up switching and using https://github.com/rzajac/angularjs-slider for our solution.

**Comment by PowerKiKi** [comment]
Closing since there seems to be a workaround
