### ISSUE TITLE
model to define steps array with numbers to allow slider to snap into defined numbers only

### ISSUE THREAD

**Issue by dadoadk** [angular-ui/ui-slider#90]
Is there a way to define an array of numbers to be step values. In example [5,9,16,30,34,45,60], and have slider snap only into these numbers? 
So, instead of defining step="10" , to have stepValues="5,9,16,30,34,45,60", or have a model in scope
$scope.sliderModel = {
      value:30,
      stepValues:[5,9,16,30,34,45,60]
}

**Comment by PowerKiKi** [comment]
Since this project use jQuery UI Slider, you should first have a look there if it is possible...
